name: PowerPlatformBuild

on:
  push:
    branches:
      - main
    paths:
      - 'solutions/**/src/**'
      - 'data/config/config-data.zip'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Power Platform CLI
        uses: ./.github/actions/install-pac-cli

      - name: Pack and upload MoJ Shared Base
        uses: ./.github/actions/pack-solution
        with:
          solution_unique_name: ${{ vars.SOLUTION_A_UNIQUE_NAME }}

      - name: Pack and upload MoJ Shared Automation
        uses: ./.github/actions/pack-solution
        with:
          solution_unique_name: ${{ vars.SOLUTION_B_UNIQUE_NAME }}

      - name: Pack and upload LADMS Apps
        uses: ./.github/actions/pack-solution
        with:
          solution_unique_name: ${{ vars.SOLUTION_C_UNIQUE_NAME }}

      - name: Upload config data artifact
        if: hashFiles('data/config/config-data.zip') != ''
        uses: actions/upload-artifact@v7
        with:
          name: config-data
          path: data/config/config-data.zip
          retention-days: 30
