name: Test PAC CLI Install Action

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Power Platform CLI
        uses: ./.github/actions/install-pac-cli

      - name: Verify
        shell: pwsh
        run: |
          pac --version
          pac data
